name: ep_cf_operation
description: A new Flutter application.

version: 2.1.1+11

#2.1.1+11 Modify home layout and allow backdate only 1 day
#2.1.0+10 Add Feed Consumption
#2.0.0+9 Remove google play
#1.1.3+8 Change global url
#1.1.2+7 Update sdk
#1.1.1+6 Change mortality icon
#1.1.0+5 Add weighing schedule
#1.0.3+4 Change date entry allow 2 days only (today, yesterday), add mortality remark
#1.0.1+2 Change mortality icon and remove google sign in

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  rxdart: ^0.22.0
  provider: ^2.0.1
  intl: ^0.15.8
  font_awesome_flutter: ^8.12.0
  package_info: ^0.4.0+13
  uuid: ^2.0.1
  toast: ^0.1.3
  vibration: ^1.2.4
  barcode_scan: ^2.0.1
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  sqflite: ^1.1.5

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcon
      fonts:
       - asset: fonts/CustomIcon.ttf
