name: ep_cf_operation
description: A new Flutter application.

version: 1.1.0+5

#1.1.0+5 Add weighing schedule
#1.0.3+4 Change date entry allow 2 days only (today, yesterday), add mortality remark
#1.0.1+2 Change mortality icon and remove google sign in

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  rxdart: ^0.22.0
  provider: ^2.0.1
  intl: ^0.15.8
  font_awesome_flutter: ^8.4.0
  package_info: ^0.4.0+3
  flutter_auth_buttons: ^0.5.0
  uuid: ^2.0.1
  toast: ^0.1.3
  vibrate: ^0.0.4
  barcode_scan: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  sqflite: ^1.1.5

flutter:
  uses-material-design: true
